version: '3'

services:
  leapsome-db:
    image: 'postgres:14'
    env_file:
      - .env
    volumes:
      - leapsome-db-data:/var/lib/postgresql/data
    ports:
      - '5477:5432'
    networks:
      - leapsome-net

networks:
  leapsome-net:

volumes:
  leapsome-db-data:
